insert into Korisnik(korisnicko_ime, lozinka, uloga) values ('ceks', 'ceks', 'Zaposleni');
insert into Korisnik(korisnicko_ime, lozinka, uloga) values ('ceks1', 'ceks', 'Zaposleni');
insert into Korisnik(korisnicko_ime, lozinka, uloga) values ('ceks2', 'ceks', 'Zaposleni');
insert into Korisnik(korisnicko_ime, lozinka, uloga) values ('ceks3', 'ceks', 'Klijent');
insert into Zaposleni(id, ulogaZ) values (1, 'Salterusa');
insert into Zaposleni(id, ulogaZ) values (2, 'Super_salterusa');
insert into Zaposleni(id, ulogaZ) values (3, 'Administrator');
insert into Klijent(id, vrsta) values (4, 'F');
insert into Privilege(name) values ('promenaLozinke');
insert into Privilege(name) values ('registracijaSalteruse');
insert into Privilege(name) values ('registracijaKlijentaFizicko');
insert into Privilege(name) values ('registracijaKlijentaPravno');
insert into Privilege(name) values ('preuzmiZaposlenog');
insert into Privilege(name) values ('preuzmiKlijenta');
insert into Role(name) values ('klijentRole');
insert into Role(name) values ('adminRole');
insert into Role(name) values ('salterusaRole');
insert into Role(name) values ('superSalterusaRole');
insert into Roles_privileges(role_id, privilege_id) values (1, 1);
insert into Roles_privileges(role_id, privilege_id) values (1, 6);
insert into Roles_privileges(role_id, privilege_id) values (2, 2);
insert into Roles_privileges(role_id, privilege_id) values (2, 1);
insert into Roles_privileges(role_id, privilege_id) values (3, 1);
insert into Roles_privileges(role_id, privilege_id) values (3, 3);
insert into Roles_privileges(role_id, privilege_id) values (4, 1);
insert into Roles_privileges(role_id, privilege_id) values (4, 4);
insert into Roles_privileges(role_id, privilege_id) values (2, 5);
insert into Roles_privileges(role_id, privilege_id) values (3, 5);
insert into Roles_privileges(role_id, privilege_id) values (4, 5);
insert into Korisnicke_roles(korisnik_id, role_id) values (1, 3);
insert into Korisnicke_roles(korisnik_id, role_id) values (2, 4);
insert into Korisnicke_roles(korisnik_id, role_id) values (3, 2);
insert into Korisnicke_roles(korisnik_id, role_id) values (4, 1);
